name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Copy files via SSH using sshpass
      env:
          environment: SSH_PASSWORD
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no -p 8022 jari@leffe.science.uva.nl << 'EOF'
          echo 'SSH connection successful'
          # Add your commands here
          cd /web/jari/
          /web/jari/executeUpdate.sh
          # Additional commands can be added here
        EOF

