name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files via SSH
      run: |
        scp -P 8022 -r . jari@leffe.science.uva.nl:/web/jari/BabylonSignLab

    - name: SSH and Deploy
      run: |
        ssh -p 8022 jari@leffe.science.uva.nl << 'EOF'
          cd /web/jari/BabylonSignLab
          npm install
          pm2 restart all  # assuming you use PM2 to manage your Node.js process
        EOF
