name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Copy files via SSH using sshpass
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        echo $SSHPASS
        sshpass -e scp -o stricthostkeychecking=no -P 8022 -r . jari@leffe.science.uva.nl:/web/jari/BabylonSignLab

    - name: SSH and Deploy using sshpass
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no -p 8022 jari@leffe.science.uva.nl << 'EOF'
          cd /web/jari/BabylonSignLab
        EOF
