name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Copy files via SSH using sshpass
      env:
          environment: SSH_PASSWORD
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        echo $SSHPASS
        sshpass -e scp -o stricthostkeychecking=no -P 8022 -r /home/runner/work/BabylonSignLab/BabylonSignLab jari@leffe.science.uva.nl:/web/jari/BabylonSignLab
