# name: Deploy on Leffe

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Install sshpass
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y sshpass

#     - name: Copy files via SSH using sshpass
#       env:
#         SSHPASS: ${{ secrets.SSH_PASSWORD }}
#       run: |
#         sshpass -e ssh -o StrictHostKeyChecking=no -p 8022 jari@leffe.science.uva.nl << 'EOF'
#           echo 'SSH connection successful'
#           cd /web/jari/BabylonSignLab
#           /web/jari/executeUpdate.sh
#           EXIT_CODE=$?
#           if [ $EXIT_CODE -ne 0 ]; then
#             echo "Deployment failed."
#             exit $EXIT_CODE
#           else
#             echo "Deployment succeeded."
#           fi
#         EOF
