name: Deploy on Leffe

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Echo something
      run: echo something

    - name: Send URL call to Leffe
      run: curl -X GET https://leffe.science.uva.nl:8043/githubCli/
